host=127.0.0.1
port=4000
user=root
password=''
tcount=32
tsize=10000000
threads=xxxxxx
dbname=sbtest1

# report interval
interval=10

# max time in seconds
maxtime=600

# just large enough to fit maxtime
requests=2000000000

driver=mysql
